import { v4 as uuidv4 } from 'uuid'

const nameList = [
  'Time',
  'Past',
  'Future',
  'Dev',
  'Fly',
  'Flying',
  'Soar',
  'Soaring',
  'Power',
  'Falling',
  'Fall',
  'Jump',
  'Cliff',
  'Mountain',
  'Rend',
  'Red',
  'Blue',
  'Green',
  'Yellow',
  'Gold',
  'Demon',
  'Demonic',
  'Panda',
  'Cat',
  'Kitty',
  'Kitten',
  'Zero',
  'Memory',
  'Trooper',
  'XX',
  'Bandit',
  'Fear',
  'Light',
  'Glow',
  'Tread',
  'Deep',
  'Deeper',
  'Deepest',
  'Mine',
  'Your',
  'Worst',
  'Enemy',
  'Hostile',
  'Force',
  'Video',
  'Game',
  'Donkey',
  'Mule',
  'Colt',
  'Cult',
  'Cultist',
  'Magnum',
  'Gun',
  'Assault',
  'Recon',
  'Trap',
  'Trapper',
  'Redeem',
  'Code',
  'Script',
  'Writer',
  'Near',
  'Close',
  'Open',
  'Cube',
  'Circle',
  'Geo',
  'Genome',
  'Germ',
  'Spaz',
  'Shot',
  'Echo',
  'Beta',
  'Alpha',
  'Gamma',
  'Omega',
  'Seal',
  'Squid',
  'Money',
  'Cash',
  'Lord',
  'King',
  'Duke',
  'Rest',
  'Fire',
  'Flame',
  'Morrow',
  'Break',
  'Breaker',
  'Numb',
  'Ice',
  'Cold',
  'Rotten',
  'Sick',
  'Sickly',
  'Janitor',
  'Camel',
  'Rooster',
  'Sand',
  'Desert',
  'Dessert',
  'Hurdle',
  'Racer',
  'Eraser',
  'Erase',
  'Big',
  'Small',
  'Short',
  'Tall',
  'Sith',
  'Bounty',
  'Hunter',
  'Cracked',
  'Broken',
  'Sad',
  'Happy',
  'Joy',
  'Joyful',
  'Crimson',
  'Destiny',
  'Deceit',
  'Lies',
  'Lie',
  'Honest',
  'Destined',
  'Bloxxer',
  'Hawk',
  'Eagle',
  'Hawker',
  'Walker',
  'Zombie',
  'Sarge',
  'Capt',
  'Captain',
  'Punch',
  'One',
  'Two',
  'Uno',
  'Slice',
  'Slash',
  'Melt',
  'Melted',
  'Melting',
  'Fell',
  'Wolf',
  'Hound',
  'Legacy',
  'Sharp',
  'Dead',
  'Mew',
  'Chuckle',
  'Bubba',
  'Bubble',
  'Sandwich',
  'Smasher',
  'Extreme',
  'Multi',
  'Universe',
  'Ultimate',
  'Death',
  'Ready',
  'Monkey',
  'Elevator',
  'Wrench',
  'Grease',
  'Head',
  'Theme',
  'Grand',
  'Cool',
  'Kid',
  'Boy',
  'Girl',
  'Vortex',
  'Paradox',
]

function generate() {
  return nameList[Math.floor(Math.random() * nameList.length)]
}
export const name = generate

const color = ['blue', 'green', 'gray', 'red', 'pink', 'purple', 'black']
export function randomColor() {
  return color[Math.floor(Math.random() * color.length)]
}

const messageText =
  'Lorem ipsum 🛫🛫🛬🛬🚀dolor sit amet, consect🥴🥴😠😠🤓🤓etur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magn🥴🥴😠😠🤓🤓a aliqua. Ut enim ad🥴🥴😠😠🤓🤓 minim veniam🚀🚀🚀🚁🚁, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo😂😂💻💻do consequat. Duis aute😀😀😀 irure dolor in reprehenderit in voluptate velit esse🥴🥴😠😠🤓🤓 cillum dolore eu fugiat nulla pariatur🪄🪄🪄🎉🎉🎊🎊. Excepteur sint occaecat cupidat🥴🥴😠😠🤓🤓at non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.🎊🎊😵‍💫😵‍💫😵‍💫🥴Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusa🥴🥴😠😠🤓🤓ntium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vita✈️✈️✈️✈️e dicta su😾😾😹😹😹⛹🏿‍♂️nt explicabo. Nemo en🥴🥴😠😠🤓🤓im ipsam voluptatem quia voluptas sit aspernatur aut odit aut f🥴🥴😠ugit, sed quia ⛹🏿‍♂️🚴🏿‍♂️🚴🏿‍♂️consequuntur magni dolores eos qui ratione voluptatem sequi nesci✈️✈️✈️✈️unt. Neque porro quisquam est, qui dolorem ipsum quia dolor 🚴🏿🚴🏿🚴🏿🚴🏿🚵🏿‍♀️sit amet, consectetur✈️✈️✈️✈️, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam qua🚵🏿‍♀️🚵🏿‍♀️🚵🏿‍♀️🚵🏿‍♀️🥥erat voluptatem. Ut enim ad minima veniam, quis nostrum exerci😾😹😹😹⛹🏿‍♂️tationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequat🥥🥝🍋🍋🍁🍁ur? Quis autem vel eum iure repreh🚓🚓✈️✈️✈️✈️✈️enderit qui in ea voluptat✈️✈️✈️✈️e velit esse quam nihil molestiae conseq✈️✈️✈️✈️uatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'

export const randomMessage = () => {
  const randNum = Math.floor(Math.random() * messageText.length - 30)
  return messageText.slice(randNum, randNum + 30)
}

export const mainSection = [
  { name: 'Home', icon: '' },
  { name: 'Shorts', icon: '' },
  { name: 'Subscriptions', icon: '' },
]
export const secondarySection = [
  { name: 'Library', icon: '' },
  { name: 'History', icon: '' },
  { name: 'Your videos', icon: '' },
  { name: 'Watch later', icon: '' },
  { name: 'Liked videos', icon: '' },
]
export const exploreSection = [
  { name: 'Trending', icon: '' },
  { name: 'Shopping', icon: '' },
  { name: 'Music', icon: '' },
  { name: 'Movies', icon: '' },
  { name: 'Live', icon: '' },
  { name: 'Gaming', icon: '' },
  { name: 'News', icon: '' },
  { name: 'Sports', icon: '' },
  { name: 'Learning', icon: '' },
  { name: 'Fashion & Beauty', icon: '' },
]

export const commentsList = [
  {
    id: uuidv4(),
    name: name(),
    comments: 'Nice video...',
    replies: [
      {
        id: uuidv4(),
        name: name(),
        comments: 'Nice video...',
        replies: [],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: 'Such an awesome content😍😍',
        replies: [
          {
            id: uuidv4(),
            name: name(),
            comments: '😍😍😍😍😍😍',
            replies: [
              {
                id: uuidv4(),
                name: name(),
                comments: randomMessage(),
                replies: [
                  {
                    id: uuidv4(),
                    name: name(),
                    comments: 'This was amazing.',
                    replies: [
                      {
                        id: uuidv4(),
                        name: name(),
                        comments: randomMessage(),
                        replies: [],
                      },
                    ],
                  },
                  {
                    id: uuidv4(),
                    name: name(),
                    comments: '😍😍😍😍😍😍',
                    replies: [],
                  },
                ],
              },
            ],
          },
          {
            id: uuidv4(),
            name: name(),
            comments: randomMessage(),
            replies: [
              {
                id: uuidv4(),
                name: name(),
                comments: randomMessage(),
                replies: [
                  {
                    id: uuidv4(),
                    name: name(),
                    comments: randomMessage(),
                    replies: [],
                  },
                  {
                    id: uuidv4(),
                    name: name(),
                    comments: randomMessage(),
                    replies: [],
                  },
                ],
              },
              {
                id: uuidv4(),
                name: name(),
                comments: randomMessage(),
                replies: [],
              },
            ],
          },
          {
            id: uuidv4(),
            name: name(),
            comments: randomMessage(),
            replies: [],
          },
        ],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: 'This was amazing.',
        replies: [],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: '😍😍😍😍😍😍',
        replies: [],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: randomMessage(),
        replies: [],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: randomMessage(),
        replies: [],
      },
    ],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: 'Such an awesome content😍😍',
    replies: [
      {
        id: uuidv4(),
        name: name(),
        comments: 'This was amazing.',
        replies: [],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: '😍😍😍😍😍😍',
        replies: [
          {
            id: uuidv4(),
            name: name(),
            comments: 'This was amazing.',
            replies: [
              {
                id: uuidv4(),
                name: name(),
                comments: 'This was amazing.',
                replies: [
                  {
                    id: uuidv4(),
                    name: name(),
                    comments: 'This was amazing.',
                    replies: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: uuidv4(),
        name: name(),
        comments: randomMessage(),
        replies: [],
      },
    ],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: 'This was amazing.',
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: '😍😍😍😍😍😍',
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
  {
    id: uuidv4(),
    name: name(),
    comments: randomMessage(),
    replies: [],
  },
]
